### ISSUE TITLE
[SOSSISSE] Replace CONTACT_FRAMES with BASELINE_INTS and TRANSIT_INTS

### ISSUE THREAD

**Issue by njcuk9999** [njcuk9999/sossisse#17]
Need to place constant `CONTACT_FRAMES` with `BASELINE_INTS` and `TRANSIT_INTS`

These are the comments:
```yaml
# Integrations used to construct a model PSF. 
#     This should be a list of [start, end] lists
#     Ideally, these would be out-of-transit (if any) and without flares. 
#     If you observed constantly a variable object (brown dwarf, phase curve), 
#     you should enter the first to last as frame IDs, except significant 
#     flares.
#     Note that on a first pass of data reduction, you may not know the 
#     optimal parameters. You can enter a guess and fine-tune in a second step. 
#     As a starting point, BASELINE_INTS can be [0, NINTS-1] where NINTS can
#     be found in your fits header.
#     Note the 1st frame is zero (pythonic numbering)
BASELINE_INTS:
  - [0, 89]
  - [111, 9999]

# If there are transit(s)/eclipse(s) in the data, enter the frames 
#     corresponding to either the 1st, 2nd, 3rd and 4th contact [length 4 list]
#     or the 1st to 4th contact [length 2 list]. 
#     These should not overlap with the BASELINE_INTS, 
#     but there may be some domain that is neither because of flares 
#     (i.e., not within a transit but not within baseline). 
#     You can enter a guess and fine-tune in a second step.
#     Note the 1st frame is zero (pythonic numbering)
TRANSIT_INTS:
  - [90, 97, 103, 110]

```
